version: '3.9'
services:
  app:
    image: cosmtrek/air
    container_name: google_form_app
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: google_form_pg
    environment:
      - POSTGRES_USER=google_form_admin
      - POSTGRES_PASSWORD=updateme
      - POSTGRES_DB=google_form
    volumes:
      - ./pg_data:/var/lib/postgresql

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - db